name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify generated files exist
        run: |
          echo "Checking contents of resources/js..."
          ls -R resources/js

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Configure Database for SQLite
        run: |
          php artisan config:clear
          php artisan config:cache
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /home/runner/work/task_and_list_app/task_and_list_app/database/database.sqlite

      - name: Run Migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /home/runner/work/task_and_list_app/task_and_list_app/database/database.sqlite

      - name: Generate Wayfinder Types
        run: php artisan wayfinder:generate --with-form
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /home/runner/work/task_and_list_app/task_and_list_app/database/database.sqlite

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest
